export const listOfExercises = [
  'Bench Press',
  'Incline Bench Press',
  'Dumbbell Bench Press',
  'Dumbbell Incline Press',
  'Overhead Press',
  'Dumbbell Shoulder Press',
  'Push ups',
  'Close Grip Bench Press',
  'Dips',
  'Tricep Extension',
  'Pull ups',
  'Chin ups',
  'Lat Pull down',
  'Barbell Bent over Row',
  'Dumbbell Single arm Row',
  'Seated Cable Row',
  'Face Pulls',
  'Deadlifts',
  'T Bar Row',
  'Hammer Curls',
  'Bicep Curls',
  'Squats',
  'Front Squats',
  'Deadlift Variations',
  'Leg Press',
  'Lunges',
  'Step ups',
  'Calf Raises',
  'Leg Curls',
  'Leg Extensions',
  'Bulgarian Split Squats',
  'Planks',
  'Side Planks',
  'Russian Twists',
  'Leg Raises',
  'Hanging Knee Raises',
  'Sit ups',
  'Crunches',
  'Cable Woodchops',
  'Medicine Ball Slams',
  'Ab Rollouts',
  'Clean and Press',
  'Thrusters',
  'Power Cleans',
  'Snatch',
  'High Pulls',
  'Kettlebell Swings',
  'Turkish Get ups',
  "Farmer's Walks",
  'Push Press',
  'Wall Balls',
  'Cuban rotations',
];
